### ISSUE TITLE
Sporadic failures due to ManagementException

### ISSUE THREAD

**Issue by ChrisLGardner** [pester/AzureDevOpsExtension#10]
Bringing over from: https://github.com/rfennell/AzurePipelines/issues/364

@bergmeister is this still occurring for you? Or should we close this for now and deal with it if it reappears?

**Comment by bergmeister** [comment]
Cannot say as it happened in the AzDo project of my previous company. But given that it's 2 years old I think we should close it for now

**Comment by ChrisLGardner** [comment]
I figured that might be the case. No one else has reported it since then so maybe it got fixed in some other work I did.
