### ISSUE TITLE
Codecoverage not possible 

### ISSUE THREAD

**Issue by esiebes** [pester/AzureDevOpsExtension#19]
#Codecoverage not possible 

###Azure Devops version: 
Onpremise  Version Dev17.M153.3

###Version of Extension/Task: 
Pester Test Runner 9.1.14

###Expected behaviour:

When the Code Coverage Output File field is filled with a valid Codecoverage result file path and the Code Coverage Folder field is filled, the task should produce a code coverage result.

###Actual behaviour

When the Code Coverage Output File field is filled with a valid Codecoverage result file path and the Code Coverage Folder field is filled, no code coverage result is produced. Only a warning is visible in the log 
"WARNING: Code coverage output not supported on Pester versions before 4.0.4." 

###Steps to reproduce the problem
Fill the following field with valid folder and/or filelocations:

Scripts Folder or Script: $(Build.SourcesDirectory)\Tests\*
Results File: $(Build.SourcesDirectory)\Test-Pester.xml
Code Coverage Output File: $(Build.SourcesDirectory)\CodeCoverage.xml
Code Coverage Folder: $(Build.SourcesDirectory)\Source\*.psm1

Run the task in a build. No codecoverage result is produced.

###Cause and proposed fix:
####Cause:
The If-statement

`` if ($CodeCoverageOutputFile -and (Get-Module Pester).Version -ge [Version]::Parse('4.0.4')) {##....}

always failes because the module Pester isn't imported in the scope of the current Pester.ps1 script yet, but only in the scope of the HelperModule.psm1. Get-Module Pester results in Null.
This in turn causes the code to proceed to the else block which produces the warning: 
"WARNING: Code coverage output not supported on Pester versions before 4.0.4." 

https://github.com/pester/AzureDevOpsExtension/blob/master/Extension/task/Pester.ps1#L113

####Proposed fix:

Add a Global switch to the Import-Module function of the Import-Pester functions to make Pester also available to the parent script:
Import-Module -Name Pester -RequiredVersion $NewestPester.Version -Verbose:$false -Global
https://github.com/pester/AzureDevOpsExtension/blob/master/Extension/task/HelperModule.psm1#L66

Import-Module -Name (Join-Path $PSScriptRoot "4.10.1\Pester.psd1") -Force -Verbose:$false -Global
https://github.com/pester/AzureDevOpsExtension/blob/master/Extension/task/HelperModule.psm1#L70
https://github.com/pester/AzureDevOpsExtension/blob/master/Extension/task/HelperModule.psm1#L49

Explanation Global switch:

"Indicates that this cmdlet imports modules into the global session state so they are available to all commands in the session.

By default, when Import-Module cmdlet is called from the command prompt, script file, or scriptblock, all the commands are imported into the global session state.

When invoked from another module, Import-Module cmdlet imports the commands in a module, including commands from nested modules, into the calling module's session state. "

https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/import-module?view=powershell-7#parameters

**Comment by ChrisLGardner** [comment]
Thanks for catching this, it's a side effect of moving it to a different module. If you've got some time then please put in a PR for this, if not then I'll try to get some time to do it this weekend or early next week.

**Comment by esiebes** [comment]
Hello Chris,
Thanks in advance, i will creatie a pr totdat.


With regards,
Edwin

Op vr 15 mei 2020 10:49 schreef Chris Gardner <notifications@github.com>:

**Comment by ChrisLGardner** [comment]
Released as 9.1.16
