### ISSUE TITLE
Does not accept spaces in paths for the Pre-Test Scriptblock

### ISSUE THREAD

**Issue by fmad** [pester/AzureDevOpsExtension#31]
### Where are you running it?
- Azure DevOps Service (VSTS)

### Version of Extension/Task
Current public version

### Expected behaviour and actual behaviour
Execute a Pre-Test Script whose path contains spaces, such as the one passed here:
`ScriptBlock d:\a\r1\a\_DeploymentTools\Deployment Tools\ARM\01_DebugARM_Init.ps1`
Fails with
```
##[error]Exception calling "Invoke" with "0" argument(s): "The term 'd:\a\r1\a\_DeploymentTools\Deployment' is not recognized 
as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was
```
### Steps to reproduce the problem
Just try to invoke a pre-test script in a path that has a space in it.

**Comment by ChrisLGardner** [comment]
Thanks for reporting this. I'd intended this functionality to just be a bunch of text rather than a file but I can easily fix that. I'll see if I can get it implemented this week.

**Comment by fmad** [comment]
Just to update w/ further testing: what seems to be happening here is that whatever is passed in this parameter will be "concatenated" w/ the remaining parameters and PowerShell will then get confused with the spaces. HOWEVER, if I *do* put in the { } around what I enter in here, it is passed as a proper scriptblock. So, probably my fault here but still something that may be easy to miss, the fact that you actually NEED to enter the { } around whatever instruction(s) you enter in this field...

**Comment by ChrisLGardner** [comment]
There should now be support for specifying a path to a file as part of the pre-test scriptblock and it'll work the same as specifying a scriptblock would.
