### ISSUE TITLE
Update of task-lib update

### ISSUE THREAD

**Issue by FStolar** [pester/AzureDevOpsExtension#32]
## 1. General summary of the issue

Hi,

We are facing a warning in pester task:

(node:4544) Warning: Use Cipheriv for counter mode of aes-256-ctr
(node:4544) Warning: Use Cipheriv for counter mode of aes-256-ctr
(node:4544) Warning: Use Cipheriv for counter mode of aes-256-ctr
(node:4544) Warning: Use Cipheriv for counter mode of aes-256-ctr
(node:4544) Warning: Use Cipheriv for counter mode of aes-256-ctr
(node:4544) Warning: Use Cipheriv for counter mode of aes-256-ctr
(node:4544) Warning: Use Cipheriv for counter mode of aes-256-ctr
(node:4544) Warning: Use Cipheriv for counter mode of aes-256-ctr
(node:4544) Warning: Use Cipheriv for counter mode of aes-256-ctr

Environment:
Custom agents on windows servers.

I probably found a solution for this to update task-lib. (https://github.com/microsoft/azure-pipelines-tasks/issues/12147)

**Comment by nohwnd** [comment]
@ChrisLGardner Moved it here, please have look.

**Comment by ChrisLGardner** [comment]
I've got a few other things to look at with the task this week so I'll make sure I get the library versions updated at the same time.

**Comment by jeremymcgee73** [comment]
Thanks! I'm seeing this as well.

**Comment by sirforce** [comment]
Looking forward to this update - seems like there could be a performance boost when this arrives in terms of pipeline processing time being reduced after the update.

**Comment by ChrisLGardner** [comment]
This should now be fixed in the latest release.
