### ISSUE TITLE
Ubuntu 20.04, permission denied at start of run

### ISSUE THREAD

**Issue by roberthstrand** [pester/AzureDevOpsExtension#46]
### Where are you running it?
- Azure DevOps Service (VSTS)

### Version of Extension/Task
10.2.3

### Expected behaviour and actual behaviour
Expected there to be no errors before actually running the tests. Errors show up right after starting pwsh:

```
##[error]mkdir: cannot create directory ‘/run/user/1001’
##[debug]Processed: ##vso[task.issue type=error;]mkdir: cannot create directory ‘/run/user/1001’
##[debug]task result: Failed
##[error]mkdir: cannot create directory ‘/run/user/1001’
##[debug]Processed: ##vso[task.issue type=error;]mkdir: cannot create directory ‘/run/user/1001’
##[debug]Processed: ##vso[task.complete result=Failed;]mkdir: cannot create directory ‘/run/user/1001’
##[error]: Permission denied

##[debug]Processed: ##vso[task.issue type=error;]: Permission denied%0A
##[debug]task result: Failed
##[error]: Permission denied

##[debug]Processed: ##vso[task.issue type=error;]: Permission denied%0A
##[debug]Processed: ##vso[task.complete result=Failed;]: Permission denied%0A
```

### Steps to reproduce the problem
Create task that runs Pester Test Runner og Ubuntu 20.04.

[Log](https://dev.azure.com/robstrdev/tftools/_build/results?buildId=16&view=logs&j=275f1d19-1bd8-5591-b06b-07d489ea915a&t=f969aa47-2434-555b-2817-6587663ed32a&l=11)

### Temporary solution
Task work fine on Ubuntu 18.04. Haven't tried 16.04 but my guess is that the issue is present on Ubuntu 20.04 only.

**Comment by ChrisLGardner** [comment]
Does this happen with the normal PowerShell task too? I think my test suite runs on 18.04 so I've not hit this. If it's an issue for the PowerShell task too then that'll show an underlying issue with either the libraries that are used by both tasks or an issue with the agent itself so we'll need to raise that elsewhere as it'll be out of my control.
________________________________

**Comment by roberthstrand** [comment]
Tried running Hello World, and the error seems to be present there as well. Didn't get flagged as an error though. 

I'll bring the message along, thanks for taking the time to answer.
