### ISSUE TITLE
Tests don't run in Yaml pipeline

### ISSUE THREAD

**Issue by gurdeepsira** [pester/AzureDevOpsExtension#49]
### Where are you running it?
*You can run the extensions in the cloud or on-premise*
- Azure DevOps Service (VSTS)

### Version of Extension/Task

Latest version from market place

### Expected behaviour and actual behaviour

I have written a yaml pipeline as below:

  - task: Pester.PesterRunner.Pester-Task.Pester@9
    displayName: 'Pester Test Runner'
    inputs:
      scriptFolder: '$(Build.SourcesDirectory)\*'
      resultsFile: '$(Build.SourcesDirectory)/Test-Pester.XML'
      CodeCoverageOutputFile: '$(Build.SourcesDirectory)/CC-Pester.XML'
      usePSCore: ${{ parameters.pscore }}
      CodeCoverageFolder: '$(Build.SourcesDirectory)'
      PesterVersion: OtherVersion
      preferredPesterVersion: 10.0.0

However, when executing the pipeline, the tests don't seem to run but the step is executed?

**Comment by ChrisLGardner** [comment]
Hi

Do you have logs of the test run you can share? One thing I noticed in your config is that you've set the pester version to 10.0.0 but the latest is only 5.0.something. It's also worth noting that the v9 of the task itself only supports Pester 4.x.x so that should error out and I'll need to look into why it's not.

**Comment by gurdeepsira** [comment]
Hi,
I modified the pipeline to this:

  - task: Pester.PesterRunner.Pester-Task.Pester@9
    displayName: 'Pester Test Runner'
    inputs:
      scriptFolder: '$(System.DefaultWorkingDirectory)/*'
      resultsFile: '$(Build.SourcesDirectory)/Test-Pester.XML'
      CodeCoverageOutputFile: '$(Build.SourcesDirectory)/CC-Pester.XML'
      usePSCore: ${{ parameters.pscore }}
      CodeCoverageFolder: '$(Build.SourcesDirectory)'
      PesterVersion: 'LatestVersion|OtherVersion'
      preferredPesterVersion: '4.10.1'


=================

The error in the pipeline is this:



StorageAccount.ps1                   8 Set-AzContext -SubscriptionId "a4d7052e…
StorageAccount.ps1                  10 New-AzResourceGroup -Name "AzPolicy_Sto…
StorageAccount.ps1                  15 Describe "Storage Account Secure Transf…
StorageAccount.ps1                  18 It "Insecure Transfer Should Not Be All…
StorageAccount.ps1                  26 $sa = New-AzStorageAccount -ResourceGro…
StorageAccount.ps1                  34 $exc = $_.Exception.Message
StorageAccount.ps1                  35 $errorThrown = $true
StorageAccount.ps1                  37 if ($exc.Contains("disallowed by policy…
StorageAccount.ps1                  39 $errorThrown = $true
StorageAccount.ps1                  40 Write-Host $exc
StorageAccount.ps1                  41 $errorThrown
StorageAccount.ps1                  41 Should -Be $true
StorageAccount.ps1                  45 $errorThrown = $false
StorageAccount.ps1                  46 $errorThrown
StorageAccount.ps1                  46 Should -Be $true
StorageAccount.ps1                  51 AfterEach {…
StorageAccount.ps1                  53 Remove-AzStorageAccount -ResourceGroupN…
vnet.ps1                             5 BeforeAll {…
vnet.ps1                             8 Set-AzContext -SubscriptionId "a4d7052e…
vnet.ps1                            10 New-AzResourceGroup -Name "StorageAccou…
vnet.ps1                            15 Describe "Storage Account Secure Transf…
vnet.ps1                            18 It "Insecure Transfer Not Allowed" {…
vnet.ps1                            24 $besubnet = New-AzVirtualNetworkSubnetC…
vnet.ps1                            26 $vnet = New-AzVirtualNetwork -ResourceG…
vnet.ps1                            30 $rule1 = New-AzNetworkSecurityRuleConfi…
vnet.ps1                            40 $errorThrown = $true
vnet.ps1                            41 Write-Host $errorThrown
vnet.ps1                            44 $errorThrown
vnet.ps1                            44 Should -Be $true
vnet.ps1                            51 AfterEach {…
vnet.ps1                            52 $afterEachVariable = 'AfterEach has bee…


Pester Script finished
Finishing: Pester Test Runner

**Comment by ChrisLGardner** [comment]
I can't see any error there. Could you attach the log file after removing anything sensitive from it? Maybe run the pipeline with the diagnostics enabled as well to get some extra details.

**Comment by gurdeepsira** [comment]
Hmm I can't see where to enable diagnostics. I will look. But is the pipeline config correct?

**Comment by ChrisLGardner** [comment]
The pipeline config looks correct. To enable the diagnostics there should be a tick box when you manually queue a build. You can also set it when manually queuing by setting some variables called system.debug to true and system diagnostic to true.
