### ISSUE TITLE
Pester Task Faling

### ISSUE THREAD

**Issue by petercharleston** [pester/AzureDevOpsExtension#50]
Running on Linux Azure Agent

Using Latest Pester Test Runner: 10.2.4 (Latest)

When i run the task with a HASH TABLE including Parameters it fails

  - task: Pester@10
    inputs:
       scriptFolder: '@{Path=’$(System.DefaultWorkingDirectory)\server.template.tests.ps1′; Parameters=@{ResourceGroupName=''$(azure_resource_group_name)''}}'
       resultsFile: '$(System.DefaultWorkingDirectory)\server.template.tests.XML'
       usePSCore: true

Failure:

##[error]Get-ChildItem: /usr/local/share/powershell/Modules/Pester/5.0.4/Pester.psm1:3165
Line |
3165 |              Get-ChildItem -Recurse -Path $p -Filter "*$Extension" -Fi …
     |              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Cannot find path
     | '/home/vsts/work/1/s/@{Path=’/home/vsts/work/1/s/' because it
     | does not exist.

##[debug]Processed: ##vso[task.issue type=error;]Get-ChildItem: /usr/local/share/powershell/Modules/Pester/5.0.4/Pester.psm1:3165%0ALine |%0A3165 |              Get-ChildItem -Recurse -Path $p -Filter "*$Extension" -Fi …%0A     |              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~%0A     | Cannot find path%0A     | '/home/vsts/work/1/s/@{Path=’/home/vsts/work/1/s/' because it%0A     | does not exist.%0A%0A
##[debug]task result: Failed
##[error]Get-ChildItem: /usr/local/share/powershell/Modules/Pester/5.0.4/Pester.psm1:3165
Line |
3165 |              Get-ChildItem -Recurse -Path $p -Filter "*$Extension" -Fi …
     |              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Cannot find path
     | '/home/vsts/work/1/s/@{Path=’/home/vsts/work/1/s/' because it
     | does not exist.

When I run the Task without parameters and modify the script to not require parameters it works:

  - task: Pester@10
    inputs:
   

  scriptFolder: '$(System.DefaultWorkingDirectory)/server.template.tests.ps1'
     resultsFile: "$(System.DefaultWorkingDirectory)/server.template.tests.XML"
     usePSCore: true
     run32Bit: False

Running in  PowerShell

Starting discovery in 1 files.

Discovery finished in 665ms.

[+] /home/vsts/work/1/s/server.template.tests.ps1
 2.36s (1.38s|344ms)

Tests completed in 2.39s

Tests Passed: 1, 
Failed: 0, 
Skipped: 0 
NotRun: 0

Pester Script finished
Finishing: Pester

**Comment by ChrisLGardner** [comment]
That'll be because Pester 5.0 doesn't support the hashtable syntax for passing parameters to tests (or parameters on tests at all). There's work to add that for 5.1 but it's not there yet.

If you need it and aren't using any other 5.0 features then you can set the task version to 9 and it'll use Pester 4.x where that syntax is accepted

**Comment by petercharleston** [comment]
Hi Chris,

thanks alot for this.

I have made the change to use Pester 4 and it is now working:

- task: Pester@9
    inputs:
      scriptFolder:
"@{Path='$(System.DefaultWorkingDirectory)/server.template.tests.ps1';
Parameters=@{ResourceGroupName='$(azure_resource_group_name)'}}"
      resultsFile:
"$(System.DefaultWorkingDirectory)/server.template.tests.XML"
      usePSCore: true
      run32Bit: False
      PesterVersion: 'OtherVersion'
      preferredPesterVersion: '4.10.1'


How do we pass parameters to pester 5 tests?

Regards
Peter

**Comment by ChrisLGardner** [comment]
Currently we can't. 5.1 should bring that functionality back and beta versions of that are available. I'll need to look into it closer to when it is released

**Comment by petercharleston** [comment]
Thanks for your help
