### ISSUE TITLE
our use of this extensions fails because we need it to be forced to use TLS 1.2 or higher.

### ISSUE THREAD

**Issue by garthbf** [pester/AzureDevOpsExtension#54]
Can you change this extensions script to use TLS 1.2 or higher or provide the option to set it in the extensions?

**Comment by ChrisLGardner** [comment]
I'll have a look at implementing that. Normally I'd be a bit wary of a blanket change like this but enabling higher TLS verions is definitely a good security measure.

**Comment by ChrisLGardner** [comment]
Fixed in 10.3.x and 9.4.x
