### ISSUE TITLE
Task fail on standard error

### ISSUE THREAD

**Issue by samds** [pester/AzureDevOpsExtension#56]
### Where are you running it?
Azure DevOps Services

### Expected behaviour and actual behaviour
My Pester task seems to fail because the program under test write to the standard error.
All tests passed
```
Tests completed in 59.3s


Tests Passed: 4, 
Failed: 0, 
Skipped: 0 
NotRun: 0


Pester Script finished
Finishing: Pester
```
but because my program write to the error stream (the program writes an error message if the available disk space is less than 10GiB)
```
##[error]LOW DISK SPACE.
```
the whole task fail.

I don't know if it really qualify as a bug but I'd love to have an option failOnStderr like with the PowerShell task.
In the meantime, I set `continueOnError: True`.

Thanks,
Sam

**Comment by ChrisLGardner** [comment]
I'll have a look at ways to implement this, setting `continueOnError` is going to cause you problems if the tests fail as they'll show as partially succeeded and will mean you'd have to check them every time to see if they actually did pass or not. Another option would be to redirect the error stream in your tests to null or one of the other output streams like Verbose or Information.

**Comment by ChrisLGardner** [comment]
Should be added now in 10.3.x and 9.4.x. It defaults to true so you'll need to specify it to false.

**Comment by samds** [comment]
Thanks for the feedback.
I tried with the new option `failOnStdErr: false` (version 10.3.10) and I still get the error.
Anyway, I took your first advice and I redirected the standard error stream to NUL in my Pester script.
